### ISSUE TITLE
Not able to find pyproject-local-kernel in kernel dropdown

### ISSUE THREAD

**Issue by JiangShen07** [bluss/pyproject-local-kernel#17]
Hello, thx for developing this! I tried following commands in my VSCode terminal before opening up a ipynb but still couldn't find pyproject-local-kernel. I've installed Python 3.8.19 in this project using rye. Would you know why?

rye add pyproject_local_kernel --git=https://github.com/bluss/pyproject-local-kernel
rye add --sync ipykernel
rye add jupyterlab
rye sync

![image](https://github.com/user-attachments/assets/63c8bed8-9b54-44a6-93f9-45fe44e08495)

**Comment by bluss** [comment]
This project is made for jupyterlab and I hadn't even tried in vscode or vscodium previously.

In code you can select a local virtualenv. I would recommend using that instead if possible - set up the project using rye or uv, then select the local .venv in code as the python environment to use, it should work well.

I see that you installed jupyterlab in your instructions, but still use code. jupyterlab is not used in your setup, so it shouldn't factor into this?

How to make pyproject-local-kernel work in code?

- pyproject-local-kernel needs to be installed where code will find it - that seems to be the pip install --user location maybe?
- pyproject-local-kernel is not accepted by code anyway, and I debugged this very briefly. I think it's because it's vetting all the installed kernelspecs for whether they point to a virtualenv or installation that exists or not. This project is based on being used inside jupyterlab, and the kernel command just starts with the plain `python` (not an absolute path). I think that means it's discarded from code's list of kernels it has as alternatives.

**Comment by bluss** [comment]
This package works with code's jupyter extension and I have added instructions for code in the FAQ. As noted, just using code's support for virtualenvs is usually enough though, then you don't need this package.
